In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
a = np.arange(15).reshape(3,5); a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
def ppr(arr):
    print(f'type:{type(arr)}')
    print(f'shape:{arr.shape}, dim:{arr.ndim}, dtype:{arr.dtype}')
    print(f'size:{arr.size}, itemsize:{arr.itemsize}')
    print(f'data:\n{arr}')

In [7]:
ppr(a)

type:<class 'numpy.ndarray'>
shape:(3, 5), dim:2, dtype:int32
size:15, itemsize:4
data:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [8]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
a.T.shape

(5, 3)

In [11]:
a.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])